server:
  port: 9100

spring:
   application:
     name: bus-station-web
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.postgresql.Driver              # mysql驱动包
    url: jdbc:postgresql://192.168.7.68:5432/bus-station-web?currentSchema=public&autoReconnect=true              # 数据库名称
    username: postgres
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
   rabbitmq:
     host: 192.168.7.68
     port: 5672
     username: guest
     password: guest
     listener:
       simple:
         acknowledge-mode: manual
         concurrency: 5 #并发
         max-concurrency: 10 #最大并发
     connection-timeout: 15000
   redis:
     host: 192.168.7.68
     port: 6379
     password:
feign:
  hystrix:
    enabled: true
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://192.168.7.68:7001/eureka/
  instance:
    instance-id: bus-station-web9100
    prefer-ip-address: true

mybatis:
  type-aliases-package: com.shuzhi.entity
  mapper-locations: classpath:mapper/*.xml,classpath*:sdk/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
logging:
  level:
    com.shuzhi.mapper: info

send:
  #超时时间 单位: 秒
  run-time: 20
  #重试次数
  count: 2
  #定时取数据的ceon
  led-cron: "*/5 * * * * ?"
  light-cron: "*/5 * * * * ?"
  lcd-cron: "*/5 * * * * ?"

