server:
  port: 9100

spring:
   application:
    name: bus-station-web
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.postgresql.Driver              # mysql驱动包
    url: jdbc:postgresql://192.168.8.150:5432/bus-station-web?currentSchema=public&autoReconnect=true              # 数据库名称
    username: postgres
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      rabbitmq: #RabbitMQ相关的配置
        host: 192.168.8.150
        port: 5672
        username: guest
        password: guest
        listener:
          simple:
            acknowledge-mode: manual
            concurrency: 5 #并发
            max-concurrency: 10 #最大并发
        connection-timeout: 15000
feign:
  hystrix:
    enabled: true
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eurek/

